zkrising/Tachi

database-seeds/collections/charts-jubeat.json
database-seeds/collections/songs-jubeat.json
database-seeds/scripts/package.json

A script was written to add charts and songs to the corresponsing json collections for Jubeat. Song titles and artists were manually fetched. The `chartID` strings were generated using `secrets.token_hex(20)`, and were not checked for duplicates. New additions were appended to the end of the array, with `songID` starting from `1051`. The 6 charts per song were added in difficulty order `ADV`, `BSC`, `EXT`, `HARD ADV`, `HARD BSC`, `HARD EXT`, per song. The `displayVersion` strings are derived from the first digit in the `id`. The `versions` list contains `festo` for every chart which has appeared in Jubeat Festo before December 2020; it does not assume current state. Charts removed during the running of Festo have still received the `festo` tag.

Festo update.

---

common/src/config/config.ts
common/src/config/static-config.ts
common/src/lib/schemas.ts
common/src/types.ts
database-seeds/collections/charts-jubeat.json
database-seeds/collections/folders.json
database-seeds/collections/songs-jubeat.json
database-seeds/collections/tables.json
database-seeds/scripts/.eslintrc
database-seeds/scripts/rerunners/add-jubeat-folders.js
database-seeds/scripts/rerunners/add-level-version-folders.js
database-seeds/scripts/run-tests.sh
database-seeds/scripts/test/collections.test.ts
database-seeds/scripts/test/id.test.ts
database-seeds/scripts/test/test-utils.ts
database-seeds/scripts/tsconfig.json

A script was written to add charts and songs to the corresponding json collections for Jubeat. Song titles and artists were manually fetched. The `chartID` strings were generated using `secrets.token_hex(20)`, and were not checked for duplicates. New additions were appended to the end of the array, with `songID` starting from `1080`. The 6 charts per song were added in difficulty order `ADV`, `BSC`, `EXT`, `HARD ADV`, `HARD BSC`, `HARD EXT`, per song. The `displayVersion` strings are derived from the first digit in the id. The `versions` list contains `qubell` for every chart which has appeared in Jubeat Qubell in the final version.

Jubeat Qubell update.

---

pnpm-lock.yaml
server/package.json
server/src/lib/score-import/framework/common/score-utils.test.ts
server/src/lib/score-import/framework/common/score-utils.ts

Null grades are *not* possible, and this branch is effectively untriggerable.
However, it has been triggered in the past. This is a huge failsafe.

test: Prevent null grades

---

common/src/types.ts
server/src/lib/score-import/framework/pb/game-specific-merge.ts
server/src/lib/score-import/import-types/ir/kshook-sv6c/converter.test.ts
server/src/lib/score-import/import-types/ir/kshook-sv6c/converter.ts
server/src/lib/score-import/worker/queue.ts
server/src/utils/misc.ts

this is a bandaid patch. we need to fix #395 properly at one point, by redefining what "scores" are valid for a game into GPT specific content.
This is painful as hell to do properly, so here's a temporary bandaid that sucks.

feat: store exScore from sv6c imports

---

database-seeds/collections/charts-jubeat.json

Fixes issue #658.
`festo` tag was removed from `versions` list if the chart was not present in Festo Final.

Jubeat Versions List Assumes Final State for Festo.

---

server/src/lib/score-import/import-types/file/eamusement-sdvx-csv/converter.test.ts
server/src/lib/score-import/import-types/file/eamusement-sdvx-csv/converter.ts
server/src/lib/score-import/import-types/file/eamusement-sdvx-csv/parser.ts

This is not ideal at the moment because score dedup will prevent this from taking effect for any existing PBs, but it's better than nothing.

add exscore to sdvx eamuse csv imports

---

server/src/lib/database-seeds/repo.ts
server/src/utils/misc.ts

Rather than chaining a `cd` command within `asyncExec`, we can instead utilise the `cwd` option within `child_process.exec`. This is slightly cleaner, and is also the magic sauce to make `repo.ts` run on windows (I'm so sorry). This PR splits up all the conjoined commands within `repo.ts` and instead lets typescript handle sequential execution of commands.

Modify database-seeds/repo.ts to not use cd

---

client/src/app/pages/dashboard/users/UserPage.tsx
server/src/server/router/api/v1/users/_userID/router.test.ts

Amends the react code to not pass null and adds a server test for this case (though the server was already accepting zero-length strings).

Permit empty "about me"s

---

server/src/server/router/api/v1/auth/auth.ts
server/src/server/server.ts

In newer versions of chromium (91+), `SameSite` defaults to `Lax`. The client and server run on different origins in dev, and as such `SameSite` must be explicitly set to `None`.
A `SameSite` of `None` is only permissible if the cookie is `Secure`. This therefore mandates that development in these situations is either performed with `ENABLE_SERVER_HTTPS` enabled (the default) or behind a local reverse proxy ensuring both are on a shared origin.

Fix auth cookies on newer chromium builds

---

_scripts/bootstrap.sh
database-seeds/scripts/rerunners/iidx-mdb-parse/.gitignore
database-seeds/scripts/rerunners/iidx-mdb-parse/blacklist.txt
database-seeds/scripts/rerunners/iidx-mdb-parse/dot-one-parser/parser.ts
server/package.json
server/src/lib/migration/migrations.ts
server/src/lib/migration/migrations/recalc-broken-iidx-notecounts.ts
server/src/scripts/sync-database.ts

```
light motion (dpa 529 -> 531)
brazilian fire (spn 409 -> 412, sph 673 -> 676, spa 892 -> 894, dpn 409 -> 414, dph 703 -> 707, dpa 897 -> 901)
electric massive diver (dpn 582 -> 583)
kailua HCN ver (dpn 427 -> 429)
gigant (spn 295 -> 297, dpn 315 -> 316, dpa 1067 -> 1068)
spinning around (dpn 447 -> 448, dph 857 -> 859)
dreamin train (sph 561 -> 562, spa 1185 -> 1186, dph 541 -> 543)
m1dy dynamic (dpn 491 -> 492, dph 939 -> 940)
seize the day (spn 387 -> 389, sph 694 -> 696, spa 1098 -> 1100, dpn 388 -> 393, dph 936 -> 940, dpa 1223 -> 1225)
```
No idea how this happened. There's not even any real common thread between these charts. Omnimix bugs, maybe? Who knows.
They're fixed now. This PR also has a couple changes for the mdb merge scripts to make them generally more useful.

fix: update some notecount bugs in charts-iidx

---

database-seeds/collections/songs-iidx.json
database-seeds/scripts/rerunners/add-new-primary-iidx-charts.js

This updates seed data for iidx 29 vanilla.
Revivals with modified charts still need to be dealt with, listed below.  I assume new charts need to be added for these?  Additionally the ascii titles should probably be added to `searchTerms` for songs with Japanese titles.
New charts:
7031 Somebody Like You
SP-NORMAL  OLD: 453 -> NEW: 376.
SP-HYPER  OLD: 678 -> NEW: 606.
SP-ANOTHER  OLD: 761 -> NEW: 933.
DP-NORMAL  OLD: 560 -> NEW: 375.
DP-HYPER  OLD: 609 -> NEW: 603.
DP-ANOTHER  OLD: 741 -> NEW: 937.
10031 SCORE
SP-NORMAL  OLD: 601 -> NEW: 595.
SP-HYPER  OLD: 829 -> NEW: 812.
DP-NORMAL  OLD: 597 -> NEW: 591.
DP-HYPER  OLD: 828 -> NEW: 806.
DP-ANOTHER  OLD: 1100 -> NEW: 1105.
12046 mind the gap
DP-NORMAL  OLD: 380 -> NEW: 378.
DP-HYPER  OLD: 550 -> NEW: 564.
17042 Do Back Burn
SP-NORMAL …

iidx 29 update

---

client/src/_style/base.scss
client/src/components/tables/cells/TitleCell.tsx

Wow! What an unexpected PR!
Rather than using a colour gradient, use a pseudo-element with `mask-image` applied to it, allowing the original background colour to show through.
- This explicitly bumps the `<td>` up to z-index 1. As many other UI elements make use of 0-5 for general layout purposes within metronic I do not believe this to cause any issues, but this has not been extensively confirmed. Menus and modals appear to use 90+.

Use mask-image for banner transparency

---

database-seeds/collections/charts-sdvx.json
database-seeds/collections/songs-sdvx.json
database-seeds/scripts/rerunners/sdvx/add-sdvx-clear-tierlist.js

sorry this is hella old by this point
some songs seem like they're still missing from the tierlist spreadsheet, either still being voted on or idk. these songs are konaste only, so they won't be there:
* `少年リップルズ`
* `アガット`
* `[E]`
* `Welcome to the Mosh Pit`
I don't know why the other charts are missing:
```
The following lv16 charts are still missing a tier:
1856: Heartache / 心の痛み [MXM] (displayVersion: exceed)
1865: MEGALOVANIA [EXH] (displayVersion: exceed)
1883: 少年リップルズ [EXH] (displayVersion: exceed)
1885: アガット [EXH] (displayVersion: exceed)
The following lv17 charts are still missing a tier:
1859: Spider Dance / スパイダーダンス [MXM] (displayVersion: exceed)
1884: [E] [MXM] (displayVersion: exceed)
The following lv18 charts are still missing a tier:
1863: SAVE the World [MXM] …
```

update sdvx konaste

---

server/src/lib/score-import/import-types/common/api-kai/iidx/class-handler.test.ts
server/src/lib/score-import/import-types/common/api-kai/iidx/class-handler.ts
server/src/lib/score-import/import-types/common/api-kai/iidx/parser.ts
server/src/lib/score-import/import-types/common/api-kai/sdvx/class-handler.test.ts
server/src/lib/score-import/import-types/common/api-kai/sdvx/class-handler.ts
server/src/lib/score-import/import-types/common/api-kai/sdvx/parser.ts

reauthing *did not* happen in the case where class-searching failed. It happened when the iterator is called,
which is after the classHandler is curried.

fix: make kai-type-apis not spontaneously fail to sync classes

---

client/src/app/pages/dashboard/import/ImportPage.tsx
server/src/lib/score-import/framework/user-game-stats/rating.test.ts
server/src/lib/score-import/framework/user-game-stats/rating.ts
server/src/lib/score-import/framework/user-game-stats/update-ugs.ts
server/src/test-utils/misc.ts
server/src/test-utils/test-data.ts

This is one of the craziest bugs in the codebase, and it's built upon just absolutely *completely* incorrect logic in our jubility calc.
It was fetching only on *songID*, with no regard to what `game` that `songID` belonged to.
As such, the bug manifested in this awkward way:
Because the query only returned 30 results, if the user had less than 30 scores on `jubeat` **AND** happened to have scores on another game **WHERE** that songID was involved, `undefined` would seep into the reducer, resulting in NaN.
`NaN`, of course, can be stored perfectly fine in MongoDB, but **does not exist at all** in JSON, so it becomes `null`, manifesting in an insane bug where a function that CANNOT return null, seems like it's returning null.
Insane.

fix: players with less than 60 scores should still have jubility calculate

---

database-seeds/collections/songs-iidx.json

Adds alttitles for Polkamania and Zenith. Something must've changed with eAM CSVs again.

Adding alttitles for Resident CSV

---

client/src/components/layout/header/SearchBar.tsx
client/src/components/sessions/SessionCalendar.tsx
client/src/components/tables/cells/SeedsDiffCell.tsx
client/src/components/tables/seeds/SeedsQuestTable.tsx
client/src/components/tables/seeds/SeedsQuestlineTable.tsx
client/src/components/tables/seeds/SeedsTableTable.tsx

`overflow: scroll` instructs the browser to **ALWAYS** show a scrollbar. This is almost certainly not what intended. Attached is an example of this. `overflow: auto` says "we want scrollbars, but only when we actually need them". Of the `scroll` occurrences none of them appeared to be a situation where this former situation was actually the required case.

Use overflow:auto not overflow:scroll

---

database-seeds/collections/songs-sdvx.json

The changes made to songs-sdvx.json include:
- The removal of any redundant terms
- Redundancy maintained or added for songs with unusual song titles
- The addition of romanised titles for songs with Japanese titles (romanisation not necessary for in only hiragana since it represents loanwords; I simply compose the term using those)
- Official translations to English for songs with Japanese titles if applicable 
- Romanised or alternative English artist names
- Any (well-known) Vocaloid/voice-synth character names (they don't hurt being in the database but if not wanted I will remove)
- Any fixes to broken artists or titles
All terms are lower case and all special characters are retained in case a user would like to use them when typing out in romaji. I didn't deem it necessary to enter …

sdvx searchTerms overhaul + fixes

---

client/src/app/pages/dashboard/DashboardPage.tsx
client/src/app/pages/dashboard/import/BarbatosPage.tsx
client/src/app/pages/dashboard/import/BeatorajaIRPage.tsx
client/src/app/pages/dashboard/import/ChunitachiPage.tsx
client/src/app/pages/dashboard/import/FervidexPage.tsx
client/src/app/pages/dashboard/import/ITGHookPage.tsx
client/src/app/pages/dashboard/import/KsHookPage.tsx
client/src/app/pages/dashboard/import/SilentHookPage.tsx
client/src/app/pages/dashboard/import/USCDBPage.tsx
client/src/app/pages/dashboard/import/USCIRPage.tsx
client/src/app/pages/dashboard/import/WACCAMyPageScraperPage.tsx
client/src/app/pages/dashboard/users/UserSettingsPage.tsx
client/src/components/activity/Activity.tsx
client/src/components/imports/TISInfo.tsx
client/src/components/layout/header/HeaderMenu.tsx
client/src/components/layout/header/UserArea.tsx
client/src/components/layout/header/UserProfileDropdown.tsx
client/src/components/layout/screens/SplashScreen.tsx
client/src/components/user/ProfilePicture.tsx
client/src/styles/customised-bootstrap/variables.scss

The home page for users logged out of Tachi would notice a blank button... It's now fixed
The import method instructions have had alerts added to make warnings more noticeable and slightly easier to read (especially when the background is white....). Links have also had underlines attached to make them more noticeable.
The Profile Picture component is now unified, accepting a size prop and can also be rendered without a wrapping anchor.
User picture settings are now a bit clearer with the unset button more clearly stating what it will do with a red background. The deletion of your profile picture or banner now requires confirmation. Once an image has been loaded into the form, it can also now be reset. 
The reasoning for this ability to reset the form isn't primarily to provide the user …

fix: landing page ghost button

---

client/src/app/pages/dashboard/import/ChunithmSiteImportPage.tsx
client/src/app/pages/dashboard/import/ImportPage.tsx
client/src/app/pages/dashboard/import/MaimaiDXSiteImportPage.tsx
client/src/app/routes/ImportRoutes.tsx
client/src/components/activity/Activity.tsx
docs/docs/game-support/games/chunithm-Single.md
docs/docs/game-support/games/maimaidx-Single.md

- adding new versions (FESTiVAL PLUS, SUN) to the documentations for maimai DX and CHUNITHM, respectively
- add maimai DX import page to the frontend
- add CHUNITHM site import page to the frontend

fix: various fixes to the client

---

client/src/lib/game-implementations.tsx
common/src/config/game-support/chunithm.ts
common/src/config/game-support/maimai-dx.ts
common/src/config/game-support/maimai.ts

a joint PR with the chunithm sections from @beerpiss.
this adds hover text for the rating classes for all three games, and adds in dan support for chunithm. also renamed the 1st Shindan from "Shinshodan" to "1st Shindan" for consistency's sake. (i google translated the kanjis i'm sorry.)

feat: a bunch of chunithm and maimai(dx) changes

---

client/src/app/pages/dashboard/import/ImportPage.tsx
client/src/app/pages/dashboard/import/MikadoPage.tsx
client/src/app/pages/dashboard/misc/CreditsPage.tsx
client/src/app/routes/ImportRoutes.tsx
server/src/lib/builtin-clients/builtin-clients.ts

Here's a link of the hook's source code: https://github.com/adamaq01/mikado
On the discord it seemed that some people were interested in it being featured so here's the PR.
There are some places where I am not sure what to put (for example the description of the hook, since theres also Barbatos) so I put some TODOs in there. It would be great to discuss about what these should be.
Same thing for the position on the webpage etc...
Marking it as a draft until this is resolved :)

Add Mikado hook as a featured import method for SDVX

---

common/src/config/game-support/arcaea.ts
server/src/game-implementations/games/arcaea.ts

Also only take best 30 potential values into account when calculating profile rating, not best 50.

[arcaea] Add `inGameID` as a supported match type

---

common/src/config/game-support/arcaea.ts
common/src/config/game-support/maimai.ts
common/src/lib/schemas.ts
common/src/types/batch-manual.ts
database-seeds/collections/charts-arcaea.json
database-seeds/scripts/test/match-type.test.ts
server/src/lib/score-import/import-types/common/batch-manual/converter.ts

Like the branch name suggests, this was introduced because Arcaea uses string IDs and not numeric IDs like many other games, making it incompatible with `inGameID`, which needs a numeric ID.
Since maimai FiNALE chart seeds already stored `inGameStrID`s, adding the match type to the game was a nice bonus.

New match type: `inGameStrID`

---

database-seeds/collections/songs-iidx.json
database-seeds/scripts/rerunners/iidx/iidx-mdb-parse/convert.ts

Updates seed data to 20230905.
The change to convert.ts should make it easier to import new leggendaria charts.  The flag allows partial IFS files to be extracted without their parent, this should be safe because the new .1, which contains all charts, will always be in the new partial file (-p0.ifs files).

[iidx] resident final and minor script change

---

server/src/game-implementations/games/maimaidx.ts

checked up with a few friends and 100.5% seems to be the minimum for an ALL PERFECT score, so adding it as a validator for scores.
there isn't a validator for the other way around since scores higher than 100.5% can be not ALL PERFECT.

fix: extra validator for maimai DX score verification

---

database-seeds/collections/charts-chunithm.json
database-seeds/collections/songs-chunithm.json
database-seeds/scripts/rerunners/chunithm/parse-chunithm-dataset.ts

- TAG vs. Kai - Chaotic Ørder
- 曲：橘亮祐、篠崎あやと／歌：三角 葵(CV：春野 杏)、逢坂 茜(CV：大空 直美)、日向 千夏(CV：岡咲 美保) - ぽかぽか温泉音頭
- 月鈴 那知(CV:今村 彩夏) - 猛進ソリストライフ！
These songs were first released in International version.
- REDALiCE - HiGHER
- t+pazolite feat. ななひら - めっちゃ煽ってくるタイプの音ゲーボス曲ちゃんなんかに負けないが？？？？？
- Getty & Kobaryo - Breaking Dawn (feat. 棗いつき)
- Gram - Odin
- USAO - Wildfire
These songs were first released in Japan version.
- koyori（電ポルP）- 独りんぼエンヴィー
- James Landino X Akira Complex「Cytus Ⅱ」- Hydra
- Kevin Penkin feat. Nikki Simmons「Cytus Ⅱ」- Survive
- MAYA AKAI - LiftOff
- 曲：橘亮祐、篠崎あやと／歌：藍原 椿(CV：橋本 ちなみ)、早乙女 彩華(CV：中島 唯) - シンデレラディスコ
Most song with kanji titles now have romaji spellings as a `searchTerm`.

[chunithm] Update seeds to 2023-10-28, add search terms for most songs

---

database-seeds/collections/charts-chunithm.json
database-seeds/collections/charts-maimaidx.json
database-seeds/collections/songs-chunithm.json
database-seeds/collections/songs-maimaidx.json
database-seeds/scripts/rerunners/chunithm/merge-options.ts

King of Performai (KoP) is an annual competition held by Sega for its Performai rhythm game series (maimai DX, CHUNITHM, O.N.G.E.K.I.). This update adds new songs used for the qualifying rounds.
- のらねこさい feat.ricono - KHYMΞXΛ (read "[chimera](https://twitter.com/com_giko_31/status/1712314803711344947)")
Immediately available in all regions.
- rintaro soma - sølips
- koyori（電ポルP）- 独りんぼエンヴィー
- James Landino X Akira Complex「Cytus Ⅱ」- Hydra
- Kevin Penkin feat. Nikki Simmons「Cytus Ⅱ」- Survive
- MAYA AKAI - LiftOff
- 曲：橘亮祐、篠崎あやと／歌：藍原 椿(CV：橋本 ちなみ)、早乙女 彩華(CV：中島 唯) - シンデレラディスコ

[maimaidx/chunithm] Update seeds for KoP5th update, add some songs to SUN Omnimix

---

database-seeds/collections/charts-chunithm.json
database-seeds/collections/songs-chunithm.json

All new songs/charts are only available in the Japanese region currently.
- 常陸 茉子 (CV：小鳥居 夕花) 「千恋＊万花」 - 茉子の日常
- ムラサメ (CV：佐藤 みかん) 「千恋＊万花」 - キズナヒトツ
- 山本真央樹 - GEOMETRIC DANCE
- MOSAIC.WAV - Love Cheat!
- 水夏える feat.月乃 - ドーナドーナのうた
- JAM Project feat. 影山ヒロノブ・遠藤正明・きただにひろし・福山芳樹 - 未来への咆哮
- パトリシア・オブ・エンド(CV：高森奈津美)、黒木 未知(CV：仙台エリ)、夕莉 シャチ(CV：浅川悠)、明日原 ユウキ(CV：種﨑敦美)「ノラと皇女と野良猫ハート」 - ネ！コ！
- xi - Aiolos
- DJ Raisei vs. Setca. feat.nayuta - うたかたのせかいで
- linear ring - とあちゃんのおもちゃ箱
- くるぶっこちゃん - 白庭
- CHUBAY×打打だいず - REL0VE REL1VE
- Acotto - deadeye
- Fix search terms for 打打だいず - 盟月

[chunithm] Update seeds to 2.16 (2023-11-09)

---

common/src/config/game-support/iidx.ts
docs/docs/game-support/games/iidx-DP.md
docs/docs/game-support/games/iidx-SP.md
server/src/lib/score-import/import-types/ir/fervidex-static/converter.ts
server/src/lib/score-import/import-types/ir/fervidex/converter.ts
server/src/lib/score-import/import-types/ir/fervidex/parser.ts

This adds support for resident omnimix, with a few catches:
- What was originally Scripted Connection Long Mix SPA is now SPL.  This is treated as a new chart in 30-omni.
- What was originally Junglist King Long SPA and DPA is now SPH and DPH.  This is correct, it was erroneous before, but to maintain compatibility these are also treated as new charts in 30-omni.
- "Theme from Flo-jack" has bad data and is not supported in 30-omni atm (hoping ryuuou patches this).
- Deep Clear Eyes has a bug (Anothers and Hypers swapped) and not supported in 30-omni atm (hoping ryuuou patches this).
- Morning Prayer is I think also bugged (?) and not supported in 30-omni atm.
Everything else should (hopefully) be good :)

feat: support iidx omnimix 1.30.1

---

client/src/components/layout/header/Header.tsx
client/src/components/layout/header/HeaderMenu.tsx

In a previous attempt to fix a bug where the sign out button was fixed in place overlaying menu elements, I created an overflow container within the menu container which already has overflow properties applied. This results in an issue where the header always overflows across all breakpoints breaking the menus on desktop displays. The actual fix is to move the sign-out button outside of said container so it's statically positioned at the end of the offcanvas.

fix: header overflow

---

database-seeds/collections/charts-chunithm.json
database-seeds/collections/songs-chunithm.json

Marks some songs as available in SUN PLUS (International):
- しーけー - 夢と幻想の終点にて
- Team Grimoire - Superbia
- Sound piercer - 空間創造理論
- Aoi - βlαnoir
- ▽▲TRiNITY▲▽ - Night Spider
- 湊あくあ（ホロライブ）- #あくあ色ぱれっと
- 桐生一馬(黒田崇矢) - ばかみたい【Taxi Driver Edition】
- Hiro - セガサターン起動音[H.][Remix]
- LV.4 - Cult future
- 曲：Funta7／歌：星咲 あかり(CV：赤尾 ひかる)、日向 千夏(CV：岡咲 美保) - スン(マイル)フラワー～Sun(Mile)Flower
Adds some English search terms:
Both of these titles are in the original jackets for the songs: https://info-chunithm.sega.jp/5518/
- "夢と幻想の終点にて" -> "The end of dream and fantasy"
- "空間創造理論" -> "Space Creation Theory"

[chunithm] international: update seeds to 2024-01-11

---

common/src/config/game-support/iidx.ts
database-seeds/collections/folders.json
database-seeds/collections/songs-iidx.json
database-seeds/collections/tables.json
database-seeds/scripts/rerunners/iidx/iidx-mdb-parse/convert.ts
database-seeds/scripts/rerunners/iidx/iidx-mdb-parse/merge-mdb.ts
docs/docs/game-support/games/iidx-DP.md
docs/docs/game-support/games/iidx-SP.md
server/src/lib/score-import/import-types/common/eamusement-iidx-csv/parser.ts

Update for IIDX 31 eamuse csv support.
Like I tried to explain in discord, this also hopefully fixes hitch hiker2 dpa.
In IIDX 4 and 5 AC and CS, this song had a DPA chart which was just a dupe of the DPH (880 notes).  It was removed in IIDX 6.  Omnimix versions prior to 28-omni restore it.
IIDX 28 added a new DPA chart (864 notes).
It seems that there was one chart DB entry for both charts, with the old notecount.
The existing entry has been updated to have the correct notecount.  A new entry has been added with the old notecount to support 27-omni, 26-omni, 5-cs, and 4-cs.

feat: IIDX update

---

database-seeds/collections/charts-maimaidx.json
database-seeds/collections/songs-maimaidx.json
database-seeds/scripts/rerunners/maimaidx/add-maimaidx-internal-levels.ts
database-seeds/scripts/rerunners/maimaidx/parse-maimaidx-dataset.js

New songs:
- Iris - The Great Banquet
- XinG、10lulu - Redemption
- Akira Complex - Ether Second
- Cosmograph - Straight into the lights
- R Sound Design feat.向日葵 - Ring
- ツミキ feat.月乃 - インパアフェクシオン・ホワイトガアル
- Zekk - WE'RE BACK!!
- wotaku - ジェヘナ
- とあ - ツギハギスタッカート
- 暁Records - HANIPAGANDA
- litmus* - Rush-Hour
- rintaro soma - 系ぎて
- かめりあ - Λzure Vixen
Also updated chart constants for lower-level songs to the latest version.

[maimaidx] Update seeds to 2024-02-26

---

database-seeds/collections/charts-chunithm.json

https://info-chunithm.sega.com/2448/
Songs added to SUN PLUS (International):
- 小仏 凪(CV:佐倉 薫)＆月鈴 白奈(CV:高野 麻里佳)＆御形 アリシアナ(CV:福原 綾香)＆桔梗 小夜曲(CV:原田 彩楓) - Λlteration
- 森羅万象 - カリスマ煉獄天神
- ビートまりお＋あまね（COOL&CREATE）- シアワセうさぎ
- 曲：橘亮祐、篠崎あやと／歌：三角 葵(CV：春野 杏)、逢坂 茜(CV：大空 直美)、日向 千夏(CV：岡咲 美保) - ぽかぽか温泉音頭
- 曲：原田篤（Arte Refact）／歌：⊿TRiEDGE [高瀬 梨緒(CV：久保 ユリカ)、結城 莉玖(CV：朝日奈 丸佳)、藍原 椿(CV：橋本 ちなみ)] - Let's Starry Party！
- technoplanet - Singularity
- 月鈴 那知(CV:今村 彩夏) - 猛進ソリストライフ！ (ULTIMA chart added).

[chunithm] Mark songs as available in international version

---

server/src/external/mongo/db.ts
server/src/lib/migration/migrations.ts
server/src/lib/migration/migrations/add-lockedat.ts
server/src/lib/score-import/framework/import-locks/lock.ts

If a lock has been held for an hour, free it automatically instead of deadlocking someones account.
This should never happen, but it did happen to a couple of users while we were restoring the database. Weird, but better than the alternative.

feat: automatically free import locks

---

server/src/lib/score-import/framework/score-importing/validate-score.test.ts
server/src/lib/score-import/framework/score-importing/validate-score.ts

current limit: +24 hours at max

feat: disallow scores in the future

---

homepage/src/style.scss

The margin on the bottom of the container causes excess scroll on larger displays. 
This can be safely removed.

Remove unnecessary margin on container

---

database-seeds/collections/songs-iidx.json

This removes the another charts from Strong Jaeger in Infinitas, they are only available in CS and Omnimix (likely an oversight when the song was added to Infinitas)
This also adds an alt-title to Reflection Into the Eden to match eamuse CSVs

fix: IIDX metadata fixes

---

common/src/lib/schemas.ts
database-seeds/collections/charts-wacca.json
database-seeds/scripts/test/custom.test.ts
server/src/lib/score-import/import-types/common/api-kai/reauth.test.ts

Some surprising errors slipped into the seeds and weren't caught by our existing tests. I've added infrastructure to add custom checks per-game so seeds maintainers can more accurately prevent errors from slipping into the seeds.
CC @GRIM657, @MinaAngura, @beerpiss, @j1nxie, @cg505, and anyone else who is contributing to seeds
Please add some appropriate validation tests to this file, and fix all of the issues highlighted.
```
[ERR] charts-iidx.json | ON - Get on Beat (55) - DP NORMAL (8cbc49c65e02a4c72eac746ae300cdfc24f84612) | Error: versions | Versions array should not be empty as this game uses versions..
[ERR] charts-iidx.json | ON - Get on Beat (55) - SP NORMAL (5fe8688fedae2bb08e0f8a82ce4101500610f248) | Error: versions | Versions array should not be empty as this game uses …
```

feat: stricter seeds, more validation, etc.

---

client/src/lib/game-implementations.tsx
database-seeds/collections/charts-ongeki.json
database-seeds/collections/songs-ongeki.json

This is the chart mentioned in #1070; the in-game id was provided by kind people on discord.
Using the opportunity to also improve the alt titles slightly, and remove them from songs with latin titles.

fix(ongeki): restore the missing aprilfools chart

---

client/src/components/game/charts/ChartInfoFormat.tsx

#1085 is going to make Tunism's folder lists even longer. This is an attempt to make them more readable
Version sort + lexical sort + left-align (center-align makes it chaotic)
Before:
After:

fix(client): make folder lists more readable

---

database-seeds/collections/charts-chunithm.json
database-seeds/collections/songs-chunithm.json

Contains the Muse Dash update (https://info-chunithm.sega.jp/7267/) which is released at the same time for both International and Japanese regions.

[chunithm] Update seeds to 2024/05/23

---

client/src/app/pages/dashboard/users/UserIntegrationsPage.tsx

This change is completely untested!!
I think this was meant to be here since GAN and NAG were split out, but somehow got missed. I just noticed it and it looks like an obvious fix. I did this in the github web editor so I have no clue if it works lol

add links to GAN and NAG in service integration page

---

database-seeds/collections/songs-iidx.json

This marks all charts from the 2nd infinitas casthour pack as available in inf, [songlist here](https://p.eagate.573.jp/game/infinitas/2/music/index.html#pac)
It also includes the fixes for Reflection into the EDEN and Strong Jaeger from PR 1045.

feat: add casthour pack 2 songs to Infinitas

---

.dockerignore

These folders are temporary file storage from the iidx-mdb-parse script and aren't needed in the docker image.

fix: include iidx-mdb-parse file storage in dockerignore

---

database-seeds/collections/songs-iidx.json

This adds newer tier info from atwiki and updates the iidx31 seeds.
Note that a song added in iidx31 has been removed, this is handled by having an empty `versions` array.

feat: IIDX metadata update

---

common/src/types/documents.ts
database-seeds/collections/songs-chunithm.json
database-seeds/collections/songs-iidx.json
database-seeds/collections/songs-maimai.json
database-seeds/scripts/rerunners/iidx/iidx-mdb-parse/blacklist.txt
database-seeds/scripts/test/match-type.test.ts
server/src/lib/score-import/framework/common/converter-failures.ts
server/src/lib/score-import/framework/score-importing/score-importing.ts
server/src/utils/queries/songs.ts

I made the duplicate-song-title-checker work, but it's revealed that we have a hell of a lot of duplicate song titles in the database. This needs to be sorted out one way or another.
We have a fairly frustrating issue which is that the eamusement CSV imports use song title matching, but they *can't* because there are duplicate song titles in the games-in-question. This sucks, we need to do this abstraction better. Sad.

feat: make the duplicate-song-title-checker work

---

database-seeds/collections/charts-chunithm.json
database-seeds/scripts/rerunners/chunithm/merge-options.ts

- Adds LUMINOUS ep. II to LUMINOUS International: https://info-chunithm.sega.com/2779/
- Remove ULTIMA charts introduced in later versions from NEW/NEW+

[chunithm] Update seeds to 2024/07/04 and fix versions for some ULTIMA charts

---

server/src/lib/score-mutation/delete-scores.ts

closes #1129. fix tested on a local instance using the same reproduction steps as the linked issue.

fix: do not delete PB after reverting import

---

client/src/app/pages/dashboard/import/AquaArtemisExportPage.tsx
client/src/app/pages/dashboard/import/ChunithmMYTExportPage.tsx
client/src/app/pages/dashboard/import/ChunithmSiteImportPage.tsx
client/src/app/pages/dashboard/import/SaekawaPage.tsx

github gists don't do username redirects apparently.

fix: correct dead links caused by my username renaming

---

.vscode/settings.json
Dockerfile.bootstrap
Dockerfile.bot
Dockerfile.client
Dockerfile.seeds
Dockerfile.server
client/src/components/user/UGPTHeader.tsx
client/src/types/api-returns.ts
client/src/util/time.ts
server/src/server/router/api/v1/users/_userID/games/_game/_playtype/router.ts

Suggested by a couple people on discord now at this point.
Fun fact: I am almost completely unable to write the word `Playtime` with my keyboard without accidentally writing `Playtype`. The muscle memory for that is just far, far too strong in a Tachi context. Heh.

feat: Session Playtime

---

server/src/game-implementations/games/ddr.ts

The score validation using judgements is broken due to the absence of the correct hold count if some holds have been missed by the player during the song. This breaks the `stepScore` value and computes a wrong score and invalidates some scores.
Until we have a way to get the actual steps count and holds count for every single chart, this validation function must be disabled.

feat: disable score validation by judgement for DDR

---

client/src/components/tables/cells/FlareCell.tsx
client/src/lib/games/ddr.tsx
server/src/game-implementations/games/ddr.ts

Displaying Flare Rank in scores is relevant to better understand the associated Flare Skill points for a given song

feat: Display Flare Rank in DDR scores

---

common/src/lib/schemas.ts
common/src/types/batch-manual.ts
server/example/conf.json5
server/src/lib/score-import/import-types/common/batch-manual/converter.ts
server/src/utils/queries/songs.ts

This branch adds an optional `artist` field to the batch-manual spec, which gets taken into account if matching by `songTitle`. Consider it a specialized `identifier2`. I think this is the path of least resistance towards `songTitle` not sucking.
Not benchmarked because I wouldn't know how.
Tested with the import below.
There are 3 Singularities and 1 World Vanquisher in the game.
Everything is imported correctly except the `30` score, as expected, because it doesn't have an `artist` field.
```json
{
"meta": {
"game": "ongeki",
"playtype": "Single",
"service": "Test"
},
"scores": [
{
"score": 10,
"noteLamp": "LOSS",
"bellLamp": "NONE",
"matchType": "songTitle",
"identifier": "Singularity",
"difficulty": "MASTER",
"artist": "ETIA.「Arcaea」"
},
{
"score": 20,
"noteLamp": "LOSS",
"bellLamp": …
```

feat: songTitle+artist match

---

bot/src/webhookHandlers/classUpdate.ts

Pretty self-explanatory.
Class calculation is based on the best 30 scores in 3 different tiers, so you need _at least_ 90 scores to have a complete list.
Knowing that, setting the minimum to 90 for DDR isn't entirely accurate but it'll be just fine to prevent most of the spam. Once you reach that hard cap, ranks will start to evolve much, much slower.

feat: add minimum score amount to render class update for ddr

---

client/src/app/pages/dashboard/DashboardPage.tsx
client/src/app/pages/dashboard/users/UserGamesPage.tsx
client/src/components/layout/header/Header.tsx
client/src/components/layout/header/HeaderMenu.tsx
client/src/components/tables/dropdowns/PBDropdown.tsx
client/src/components/user/UGPTProfiles.tsx
client/src/components/util/query/useApiQuery.tsx

Currently, the UGS info component is used in two different ways. This new component merges the functionality of the two and simplifies the data flow.
Current behaviour fetches the game stats of the requested user whenever the component is created. This generates an unneccessary fetch everytime the component is created and, because the component isn't memoised, creates a second fetch after the component renders.
To fix this, it now chooses how to source data based on conditions:
- If a logged in user is viewing their own profiles, the stats are already available and up-to-date in context, so we can use the context to prevent asking the server.
- For viewing other profiles, it now uses react query.
One semi-important thing to note is that is that both instances currently use different …

refactor(client): unify user profile components

---

server/src/game-implementations/games/_common.ts
server/src/game-implementations/games/arcaea.test.ts
server/src/game-implementations/games/wacca.test.ts
server/src/game-implementations/types.ts
server/src/lib/score-import/framework/score-importing/validate-score.ts

feat: add chart parameter to ScoreValidator

---

client/src/app/pages/dashboard/misc/SupportMePage.tsx

ko-fi is also styled "Ko-fi" apparently, so just edited that too
was randomly browsing and saw that the "Support" page still referenced Patreon in the title, and decided to change it. Perhaps it would be better to remove it from the title completely?

fix: replace patreon reference with ko-fi

---

seeds/collections/charts-maimaidx.json
seeds/collections/tables.json

- chunithm: mark new plus folders as inactive, as mythos got sun (plus?) now.
- maimaidx: seeds update to remove songs with expired license from buddies+.
data from @beer-psi as always.

feat: maidx + chunithm seeds update

---

client/src/components/tables/cells/DDRScoreCell.tsx
common/src/config/game-support/ddr.ts
server/src/game-implementations/games/ddr.ts

Add support for several optional metrics for DDR :
- Fast/Slow/MaxCombo
- exScore, based on SDVX. Also available as a secondary score and session alg

feat: support exScore, fast, slow, maxCombo as optional metrics for DDR

---

client/src/components/game/folder/FolderDistributionTable.tsx

better lamps/grades should start from bottom,
so that the cumulative lamps/grades can be deduced more easily

fix: invert folder thermometer data direction

---

client/src/app/pages/dashboard/games/_game/_playtype/GPTLeaderboardsPage.tsx
client/src/app/pages/dashboard/users/games/_game/_playtype/OverviewPage.tsx
client/src/components/charts/TimelineChart.tsx
common/src/config/game-support/museca.ts

Fixes #1185
Other changes:
- Dropped trailing decimals for MUSECA CuratorSkill. It was always `.00`.
- Changed `TimelineGraph` margins to accommodate bigger y-values

fix(client): use the rating formatter specified in tachi-common for history graphs

---

seeds/scripts/rerunners/iidx/make-things-available-in-inf.js

Allow `scripts/rerunners/iidx/make-things-available-in-inf` to check for a match where `chart.data.inGameID` is an array.

fix: make-things-available-in-inf: chart.data.inGameID can be an array

---

client/src/components/user/UGPTStatShowcase.tsx

Currently the delta does show for percent, score and playcount on folders however lamp and grade folder showcases does not show.

Add delta to all folder stat showcases

---

common/src/config/game-support/iidx.ts
seeds/collections/folders.json
seeds/collections/tables.json
server/src/lib/score-import/import-types/ir/fervidex/parser.ts

This adds support for Epolis Omnimix 1.31.1
Carried over from Resident Omnimix, there are two unsupported songs.  I've asked for clarification about Deep Clear Eyes.  Morning Prayer might just need to be counted as a new set of charts.

feat: Epolis Omnimix support

---

client/src/app/pages/dashboard/import/WACCAMyPageScraperPage.tsx

It seems there are CSVs in the wild that use \r\n instead of just \n, which can cause this to fail. Since this check is already best-effort, just drop the newline since it doesn't really matter.
Untested. Unclear if the \r\n can cause additional downstream  serverside parsing issues that will also need to be addressed.

remove newline from MyPageScraper CSV parser check

---

client/src/components/charts/OngekiScoreChart.tsx
client/src/components/tables/dropdowns/GPTDropdownSettings.tsx
client/src/components/tables/dropdowns/components/OngekiScoreDropdownParts.tsx
common/src/config/game-support/ongeki.ts

This branch adds 3 optional graphs to Ongeki scores:
* Score−
* Missed bells
* Life gauge
The provided data is the Y axis. The X axis is presumed to increase in 1-second intervals. The score provider is trusted with padding the array with `null`s in case of an early forfeit.
Because Ongeki scores are very top-heavy, I capped score− at S (970k), the lowest score that can be considered relevant. Another option could be to scale the Y axis depending on the score.
The scale of the bell chart's Y axis depends on the number of bells that could have been obtained at the time of forfeit. If that's a blocker, one solution would be to add total bell counts to seeds and expose them to the client; alternatively, add another optional field and expect the score provider to fill it every time.

feat(ongeki): graphs

---

docs/docs/codebase/batch-manual/index.md
docs/docs/game-support/common-config/match-types.md
docs/docs/game-support/games/ongeki-Single.md

> Dany kind of forgot about documentation.
\>\>#1154
* Documented the `artist` identifier.
* Made the `songTitle` warning less scary because duplicates have been being resolved properly since #1104.
* Almost all KT GPTs enable this method so a super scary warning isn't a good look in the first place.
* Updated the Ongeki doc.

docs: document #1154 (songTitle+artist matching)

---

common/src/config/game-support/ddr.ts
common/src/lib/schemas.ts
common/src/types/batch-manual.ts
docs/docs/codebase/batch-manual/index.md
docs/docs/game-support/common-config/match-types.md
docs/docs/game-support/games/ddr-DP.md
docs/docs/game-support/games/ddr-SP.md
seeds/collections/songs-ddr.json
seeds/scripts/test/match-type.test.ts
server/src/lib/score-import/import-types/common/batch-manual/converter.ts

`ddrSongHash` is a 32-character hash used by the official DDR e-amusement website to identify a song.
I believe Tachi supported this match type in the past but I didn't look too much into it. Re-implementing this will allow users to use services that scrape DDR scores from e-amusement, such as 3icecream (however their timestamps can be unreliable; I'm working on my own tool as well).
I tried my best to figure it out without official documentation. If anything's missing, please advise!

New match type: `ddrSongHash`

---

server/src/lib/builtin-clients/builtin-clients.ts

fix: update inohara's config schema

---

common/src/config/game-support/iidx.ts
seeds/collections/songs-iidx.json
seeds/scripts/rerunners/iidx/add-2dxtra-to-normal-charts.js
seeds/scripts/rerunners/iidx/add-2dxtra.js
server/src/lib/score-import/import-types/ir/fervidex/parser.ts

This adds support for Epolis 2dxtra, and also shoehorns in some altTitles for Pinky Crush CSVs.
This is my first time adding a 2dxtra version, but it looks like everything went well?  Thanks for making it easy :)

feat: support iidx 31-2dxtra

---

common/src/config/game-support/chunithm.ts
common/src/config/game-support/ongeki.ts
server/src/game-implementations/games/chunithm.test.ts
server/src/game-implementations/games/chunithm.ts
server/src/game-implementations/games/ongeki.test.ts
server/src/game-implementations/games/ongeki.ts
server/src/game-implementations/utils/profile-calc.ts
server/src/test-utils/test-data.ts

Added a new parameter to `CalcN`. If active (I activated it for Ongeki and Chunithm, although all games with non-integer ratings are possibly affected), profile rating will be calculated using fixed-point arithmetic. This is basically https://github.com/zkrising/rg-stats/pull/10 but for profile rating.
This fixes edge cases *like my current rating* as well as these wacky rating graphs (since rating is now truncated as it should be):
If you restore `ongeki.ts:59`, i.e. `naiveRating: ProfileAvgBestN("rating", 45)`, the new tests will fail with ratings `16.269999999999996` `1.4222222222222223`. Likewise, `chunithm.ts:19`.
An alternative fix would be to re-define rating and store it multiplied by 100 in the DB but that would require fixing old scores.

fix: floating-point profile rating calculation

---

seeds/collections/charts-sdvx.json
seeds/collections/songs-sdvx.json

2 songs were made available for konaste on [10/31](https://x.com/SOUNDVOLTEX573/status/1851084470365147414)
alt title from CSV import was added from a discord bug report

update sdvx konaste seeds and add alt title

---

seeds/collections/charts-wacca.json
seeds/collections/songs-wacca.json
server/src/lib/score-import/import-types/api/myt-wacca/class-handler.ts

Contains
- 25 jan. update
- Rerates applied between initial and today
- Dans achieved on PLUS should now be imported if player has a PLUS profile

[wacca] Seeds update for PLUS, dan fixes

---

client/src/components/game/charts/ChartInfoFormat.tsx

"Contrapasso -paradiso-" doesn't search properly since - excludes paradiso as a search boolean.
https://kamai.tachi.ac/games/maimaidx/Single/songs/275/Master
This replaces all - with spaces.
Also changed maimai dx to maimaiでらくす since it yields better search results.

Replace - with space for youtube searches, adjust maimai search 

---

seeds/collections/charts-chunithm.json
seeds/collections/songs-chunithm.json

Aside from the two new songs for King of Performai 6th:
- void (Mournfinale) × 水野健治 - Aether Crest: Celestial
- MintJam vs Masahiro "Godspeed" Aoki - Crush the Dystopia
this just updates the international table to the current version. I haven't been able to catch up recently due to personal circumstances. Sorry about that.

[chunithm] Update seeds to 2025/02/27

---

bot/src/webhookHandlers/classUpdate.ts

maimai's rating is best30 and maimai DX's rating is best50, so if the user doesn't have enough scores to fill their best rating frame they will blitz through most of the lower ranks.

[bot] Add minimum threshold for maimai/maimai DX color class updates

---

client/src/lib/game-implementations.tsx

Both games use best 50 scores for rating and so any new scores in top 50 should be an important score, instead of top 30.

[chunithm/maimaidx] Fix sessionImportantScoreCount

---

client/src/components/imports/ImportFileInfo.tsx

People may just have thousands of scores in a batch manual obtained through a network export.

client: increase import file size limit to 8MB

---

common/src/config/game-support/chunithm.ts

It's best 50 scores now, not best 30.

[chunithm] Fix NaiveRating description

---

client/package.json
pnpm-lock.yaml
server/package.json

This version of rg-stats fixes a bug with maimai rating for scores between 100% and max (https://github.com/zkrising/rg-stats/pull/14).
Requires a recalc on all scores >=100%.

chore(deps): update rg-stats to 0.5.10

---

seeds/collections/charts-chunithm.json
seeds/collections/songs-chunithm.json

- teto update:
- 原口沙輔 feat.重音テト - 人マニア
- 吉田夜世 - オーバーライド
- マサラダ - ライアーダンサー
- フロクロ - 黒塗り世界宛て書簡
- ongeki collab:
- 曲：eba／歌：⊿TRiEDGE [高瀬 梨緒(CV：久保 ユリカ)、結城 莉玖(CV：朝日奈 丸佳)、藍原 椿(CV：橋本 ちなみ)] - 本能的 Survivor
- 打打だいず vs. siromaru vs. Tanchiky - 淵底のグレイ・ユークロニア
data from the amazing @beer-psi as always.

feat(seeds): update chunithm to 27/03/25

---

client/src/components/tables/components/TachiTable.tsx
client/src/components/tables/sessions/GenericSessionTable.tsx

This simple nullish check prevents `"error": "e is undefined"` when typing anything in a session search bar. Admittedly this is a band-aid fix, as the PB data is still missing, but at least it doesn't crash.

fix(client): "e is undefined" in session search

---

server/src/lib/score-import/import-types/common/api-cg/jb/converter.test.ts
server/src/lib/score-import/import-types/common/api-cg/jb/converter.ts

Patch is actually by @defvs who worked on the affected jubeat import, he sent me the patch because he does not have access to GitHub during the day.

fix: jubeat music rate rounding in GAN/NAG/CGD API imports

---

server/src/lib/score-import/import-types/common/api-cg/jb/converter.test.ts
server/src/lib/score-import/import-types/common/api-cg/jb/converter.ts
server/src/lib/score-import/import-types/common/api-cg/types.ts

Those bitfield values are taken from what the game sends - Radio told me that this is supposedly the same as what the CG API returns. **I cannot confirm it. I do not have CG API access. Please test this outside of prod.**.
I got the bitfield values from actually dumping the network calls of my own cab, there's further stuff in the MSB of the bitfield but these seem mostly useless.
Here are the bit positions:
| 31:4             | 3   | 2  | 1     | 0            |
|------------------|-----|----|-------|--------------|
| ? | EXC | FC | CLEAR | FAILED/SAVED |
I've created various tests for that as well - including the edge case of a 'challenge fail'.

fix(api-cg/jb): use clearFlag bitfield to generate Lamp

---

client/src/components/imports/MYTIntegrationPage.tsx

This PR removes the client-side requirement that MYT access codes must start with a 0 or a 3, because all FeliCa NFC devices (including stuff like headphones) can be scanned on the network, and the access codes generated for them might not start with a 0 or a 3.

[MYT] Do not check access code prefixes

---

seeds/collections/charts-wacca.json
seeds/collections/songs-wacca.json

- Contains all new songs/new difficulties from the 4.01.50 update.
- Rerated B.B.K.K.B.K.K INF and Internet Yamero EXP.

[wacca] 4.01.50 Update Seeds

---

client/src/components/charts/GekichuScoreChart.tsx
client/src/components/tables/dropdowns/GPTDropdownSettings.tsx
client/src/components/tables/dropdowns/PBDropdown.tsx
client/src/components/tables/dropdowns/ScoreDropdown.tsx
client/src/components/tables/dropdowns/components/ChunithmScoreDropdownParts.tsx
client/src/components/tables/dropdowns/components/DocumentComponent.tsx
client/src/components/tables/dropdowns/components/OngekiScoreDropdownParts.tsx
common/src/config/game-support/chunithm.ts
common/src/config/game-support/ongeki.ts
seeds/collections/songs-chunithm.json
seeds/collections/songs-ongeki.json
seeds/scripts/rerunners/ongeki/parse-song-duration.ts
server/src/test-utils/mock-db/songs-chunithm.json
server/src/test-utils/mock-db/songs-ongeki.json
server/src/test-utils/test-data.ts

Re-purposed the Ongeki score and life graphs for Chunithm. Aside from timestamps, the picture contains real data. I went with S+ baseline because Chunithm scores are extremely top-heavy.

feat(client): chunithm graphs, song durations

---

seeds/collections/charts-sdvx.json
seeds/collections/songs-sdvx.json

Re-open the PR. from
https://github.com/zkrising/Tachi/pull/1294
+ upstream seed till 2025021200
(https://github.com/zkrising/Tachi/pull/1295)
Still 5 missing song.
- The world of sound -celestial mix-
- XROSS INFECTION -xiRemix-
- 回想音楽 - Thank you for your playing music
- caramel ribbon (Tatsunoshin Remix)
- Dynasty -dal segno-
===================================
+ Accidentially upstreamed to push INFINITAS monthly update T^T 
beatmania IIDX INFINITASの楽曲公開についてご案内いたします。
2025年6月4日(水) 10時より以下の楽曲が公開となります。
■BITで解禁可能楽曲の追加
・WHA
・DENIM

seed: SDVX Konasute Song Pack vol. 25 + IIDX INF Monthly June 2025

---

client/src/components/charts/GekichumaiScoreChart.tsx
client/src/components/tables/dropdowns/GPTDropdownSettings.tsx
client/src/components/tables/dropdowns/components/ChunithmScoreDropdownParts.tsx
client/src/components/tables/dropdowns/components/MaimaiDXScoreDropdownParts.tsx
common/src/config/game-support/maimai-dx.ts
seeds/collections/songs-maimaidx.json
seeds/scripts/rerunners/maimaidx/merge-options.ts

Graph support for maimai DX's percent and life was added based on nairobi's work in #1214 #1284.
Only one graph data (either percent or life) needs to be submitted for graph to show up. This is because maimai DX life gauge is either a challenge or a track skip option that needs to be enabled explicitly.
~~The PR is feature-complete; currently in draft because I need to find duration data for removed songs.~~

feat(maimaidx): graphs and song durations

---

seeds/collections/charts-wacca.json
seeds/collections/songs-wacca.json

- Contains all new songs/new difficulties from the 4.01.75 update.
- Rerated Cheatreal EXP, Blows Up Everything EXP, Happy Synthesizer INF and Straight into the Lights EXP.

[wacca] 4.01.75 Update Seeds

---

seeds/collections/charts-sdvx.json
seeds/collections/songs-sdvx.json
seeds/scripts/rerunners/sdvx/merge-mdb.ts

Added exceed difficulty to numerous existing konaste-only songs:
2 from older updates (schrodinger's cat + caldwell 99)
5 from #1277
5 from #1297
Added 16 new songs (and fixed title for Ö<3rf10₩):
1. 庭師+Aoi - Our garden is blue.
2. BlackY feat. Risa Yuzuki - 神凪
3. xi - Golden Rotation
4. 打打だいず vs. siromaru - Titanomachia
5. kanone VS nora2r - Ardenok
6. technoplanet feat. Tamako Kinoshita - Jupiter
7. めと（Metomate） - 流転に咲く魂の花
8. ぺのれり - 黒蝶のワルツ
9. ETIA. - Gryphone
10. 星野音楽工房 - Who then no 灯
11. DECO黻27 - テレパシ
12. TJ.hangneil - 神威
13. Capchii feat. 初音ミク - What's up? Pop!
14. La prière - Crossfade
15. yuichi NAGAO - 星界のアルペジオ
16. momocaca (月乃×Capchii) - Ö<3rf10₩

feat: update sdvx seeds to 2025042202

---

client/src/components/tables/cells/IIDXLampCell.tsx

Check for the existence of `scoreData.optional.comboBreak` rather than its value in `IIDXLampCell.tsx`

fix: iidx lamp cell: check whether combobreak is nullish

---

client/src/components/user/UGPTStatsOverview.tsx
common/src/config/game-support/arcaea.ts
common/src/config/game-support/bms.ts
common/src/config/game-support/chunithm.ts
common/src/config/game-support/ddr.ts
common/src/config/game-support/gitadora.ts
common/src/config/game-support/iidx.ts
common/src/config/game-support/itg.ts
common/src/config/game-support/jubeat.ts
common/src/config/game-support/maimai-dx.ts
common/src/config/game-support/maimai.ts
common/src/config/game-support/museca.ts
common/src/config/game-support/ongeki.ts
common/src/config/game-support/pms.ts
common/src/config/game-support/popn.ts
common/src/config/game-support/sdvx.ts
common/src/config/game-support/usc.ts
common/src/config/game-support/wacca.ts
common/src/types/game-config-utils.ts
common/src/types/game-config.ts
common/src/types/internals.ts

In the live version, the score rating algorithm description only pops up if it's named exactly like the profile rating algorithm, which doesn't work with "Naive" algorithms.
Before:
After:

feat: always show score alg desc under profile alg desc

---

Dockerfile.dev

this should be `language[_territory][.codeset] codeset` according to https://wiki.archlinux.org/title/Locale

fix: correct locale entry for locale-gen

---

client/src/components/charts/GekichumaiScoreChart.tsx

My bad, I didn't account for non-integer song duration and it ended up throwing `invalid array length` in some cases.

fix(client): mistake in the previous fix

---

client/src/components/tables/cells/DifficultyCell.tsx
client/src/components/tables/cells/ScoreCell.tsx
client/src/lib/game-implementations.tsx

- maimai DX uses 4dp percentages (e.g. 100.5000%), and they're all shown to the player in-game. Most scores on Tachi are already submitted with 4dp percentages, so this merely exposes it to the user instead of having the client truncate it.
- The game has long difficulty names (`DX Master`, `DX Re:Master`) which makes the level go down a line in some cases, which does not look nice. Instead, always use the short form.
| <img width="697" height="184" alt="image" src="https://github.com/user-attachments/assets/1b143d77-2182-449a-884f-f63deb57d827" /> | <img width="778" height="173" alt="image" src="https://github.com/user-attachments/assets/0a07b33b-1627-4c52-bd7d-37381aa57a4e" /> | 
|---|---|

fix(client): shorten maimai DX difficulties, display percent as 4dp

---

seeds/collections/songs-sdvx.json
seeds/scripts/rerunners/sdvx/merge-mdb.ts

sync with game
TOYBOX CANNON doesn't display clearly in GitHub diff, but eamuse site and other sources have an extra combining character, which looks wrong when viewed on Tachi.

fix: update sdvx titles/artists

---

seeds/scripts/test/custom.test.ts

This fixes the world record data for i-ii SPA, and adds a seeds test to ensure KaidenAverage < WorldRecord.  Additionally, some minor prettier/linter fixes to the tests added in #1330.

fix: correct i-ii SPA WR, add KAVG<WR test

---

seeds/collections/songs-chunithm.json
seeds/collections/songs-maimaidx.json
seeds/collections/songs-ongeki.json

did another quick look through chuni/maimai
main points:
added tags for prism+
added missing romaji of titles when needed 
added fixes for punctation in titles (eg LLL returns no results for L.L.L.)
support both american/british english searches
I only looked at geki for 5 minutes since it seemed mostly fine

Gekichumai search tags update

---

seeds/collections/songs-iidx.json

feat: IIDX INFINITAS SDVX Song Pack Vol. 2 (Total 12 songs)
+ 5 songs from AC
- I
- Into the madness
- The Clown of 24stairs
- ZENITH
- 恋愛=精度×認識力
+ 7 INFINITAS Exclusive songs (Level SP/DP)
- sink into the dream (6/8/10 6/8/10)
- 黎明の情 (5/8/10 5/8/10)
- Metagame Matador (6/9/11 6/9/11)
- The setting sun(burst) (5/8/11 5/8/11)
- レインボウ・フレーバー (4/7/10 4/7/10)
- ドゥサンコオデッセイ!! (6/10/12 6/10/12)
- 光風霽月 (7/10/12 6/10/12)

seed: IIDX INFINITAS SDVX Song Pack Vol. 2

---

server/src/game-implementations/games/ddr.ts

Redid score validation so division is done final to avoid inaccuracies that popup when doing further calculations on floating point number. 
Tested with error cases I put in the issue and large batch manual that also previously had issues.
fixes #1334

fix: be rid of ddr floating point  inaccuracy in score validation

---

seeds/scripts/rerunners/iidx/iidx-mdb-parse/convert.ts

This addresses a few issues:
- Mid-game version 32 removals that were not marked as removed in seeds (they were removed via server flags, data is unchanged, so it's a manual process)
- Missing songs from versions 30-32 in version 33 (issue on my end)
- Missing leggendaria charts (iidx-mdb-parse was sometimes preferring original files instead of patch files, if a -p0 exists it is not just for spl/dpl charts, it is a replacement of the original .1 file)
- I forgot to add the new version of ADVANCE via the "add new primary" script.
I adjusted the logic in iidx-mdb-parse to get the desired result but I think that whole section was made with the assumption that "p0" files are *only* for spl/dpl charts rather than patches to the whole .1, so it could use some further rework.

fix: seeds corrections for iidx 32 and 33

---

seeds/scripts/rerunners/bms-pms/sync-bms-tablefolders.ts
server/src/lib/jobs/backsync-bms-pms-data.ts
server/src/lib/jobs/bms-table-sync.ts

Fixes most of changes in BMS backsync commits being table folders changing order.
Current collection will get stably sorted on next automatic update.

fix: sort saved BMS table levels
