- database-seeds/collections/tables.json
- server/src/lib/migration/migrations/update-jubeat-preferred-tables.ts
> feat(#599): Fix faulty default jubeat festo table IDs

- server/src/lib/score-import/import-types/ir/fervidex-static/parser.test.ts
- server/src/lib/score-import/import-types/ir/fervidex-static/parser.ts
- server/src/lib/score-import/import-types/ir/fervidex-static/types.ts
- server/src/lib/score-import/import-types/ir/fervidex/parser.ts
- server/src/lib/score-import/import-types/ir/fervidex/types.ts
- server/src/server/router/ir/fervidex/router.test.ts
- server/src/server/router/ir/fervidex/router.ts
- server/src/test-utils/mock-db/charts-bms.json
- server/src/test-utils/test-data.ts
> feat(#604): Fervidex dans should sync regardless of ForceStaticImport.

- client/src/app/pages/dashboard/users/games/_game/_playtype/SpecificSessionPage.tsx
- client/src/components/sessions/SessionOverview.tsx
- client/src/components/sessions/SessionRaiseBreakdown.tsx
- client/src/components/tables/cells/IndicatorsCell.tsx
- client/src/components/tables/dropdowns/GenericSessionDropdown.tsx
- client/src/components/tables/dropdowns/components/DocumentComponent.tsx
- client/src/components/tables/dropdowns/components/ScoreEditButtons.tsx
- client/src/components/tables/pbs/PBLeadingRows.tsx
- client/src/components/tables/pbs/PBTable.tsx
- client/src/components/tables/scores/ScoreTable.tsx
- client/src/components/util/Icon.tsx
> General UI/UX improvements

- database-seeds/collections/songs-iidx.json
Will add info for 24hr Endurance Race next week when the song is added
> updated IIDX data for SP18 and new additions

- bot/package.json
- bot/src/config.ts
- bot/src/utils/logger.ts
- pnpm-lock.yaml
We could also add discord submissions, but it's fine.
> feat: add seq support to the discord bot

- client/src/app/pages/dashboard/games/_game/_playtype/GPTChartPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/OverviewPage.tsx
- client/src/components/sessions/SessionOverview.tsx
- client/src/components/sessions/SessionRaiseBreakdown.tsx
- client/src/components/tables/dropdowns/components/ScoreEditButtons.tsx
Fixes #144.
this is easily the most used feature of tachi so like, mayaswell make it better.
> feat: Commenting on scores from session raise UI

- client/src/app/pages/LoginPage.tsx
- client/src/app/pages/RegisterPage.tsx
This isn't done by default and also requires some funny react nonsense.
> Reset ReCaptcha on login/register fail

- database-seeds/collections/songs-usc.json
- database-seeds/scripts/rerunners/add-usc-converts.js
There's also a new script to help for future updates 👍
> Update USC seeds with new EG converts

- server/src/lib/score-import/import-types/common/types.ts
- server/src/lib/score-import/import-types/ir/barbatos/converter.test.ts
- server/src/lib/score-import/import-types/ir/barbatos/converter.ts
- server/src/lib/score-import/import-types/ir/barbatos/parser.ts
- server/src/lib/score-import/import-types/ir/barbatos/types.ts
- server/src/server/router/ir/barbatos/router.test.ts
- server/src/test-utils/test-data.ts
> feat: barbatos sdvx6 support

- server/src/lib/database-seeds/repo.ts
- server/src/lib/jobs/update-dp-tiers.ts
> feat: Add DP tiers

- database-seeds/collections/charts-wacca.json
- database-seeds/collections/songs-wacca.json
This got missed before because the title in My Page has a capital W in `With`.
> add dive with ü

- database-seeds/collections/charts-wacca.json
- database-seeds/collections/songs-wacca.json
> [backport] add dive with ü

- client/src/app/pages/dashboard/users/games/_game/_playtype/SpecificSessionPage.tsx
> fix: empty description on sessions should set to null

- common/src/utils/util.ts
- server/src/server/router/api/v1/games/_game/_playtype/content/bms-router.test.ts
- server/src/server/router/api/v1/games/_game/_playtype/content/bms-router.ts
- server/src/server/router/api/v1/games/router.ts
> Sieglinde Tables

- client/src/util/seeds.ts
- database-seeds/scripts/package.json
- database-seeds/scripts/rerunners/iidx-mdb-parse/.gitignore
- database-seeds/scripts/rerunners/iidx-mdb-parse/HOWTO.md
- database-seeds/scripts/rerunners/iidx-mdb-parse/blacklist.txt
- database-seeds/scripts/rerunners/iidx-mdb-parse/convert.ts
- database-seeds/scripts/rerunners/iidx-mdb-parse/dot-one-parser/parser.ts
- database-seeds/scripts/rerunners/iidx-mdb-parse/dot-one-parser/types.ts
- database-seeds/scripts/rerunners/iidx-mdb-parse/merge-mdb.ts
- pnpm-lock.yaml
This PR adds a merge script for iidx-mdbs into the seeds.
> feat: add iidx-mdb-merge script

- client/src/app/pages/dashboard/users/KsHookSV6CIntegrationPage.tsx
- client/src/app/pages/dashboard/users/UserIntegrationsPage.tsx
- common/src/lib/schemas.ts
- common/src/types.ts
- server/src/external/mongo/db.ts
- server/src/external/mongo/indexes.ts
- server/src/lib/score-import/import-types/common/types.ts
- server/src/lib/score-import/import-types/converters.ts
- server/src/lib/score-import/import-types/ir/kshook-sv6c-static/converter.test.ts
- server/src/lib/score-import/import-types/ir/kshook-sv6c-static/converter.ts
- server/src/lib/score-import/import-types/ir/kshook-sv6c-static/parser.test.ts
- server/src/lib/score-import/import-types/ir/kshook-sv6c-static/parser.ts
- server/src/lib/score-import/import-types/ir/kshook-sv6c-static/types.ts
- server/src/lib/score-import/import-types/ir/kshook-sv6c/parser.ts
- server/src/lib/score-import/import-types/parsers.ts
- server/src/server/router/api/v1/users/_userID/integrations/kshook-sv6c/router.test.ts
- server/src/server/router/api/v1/users/_userID/integrations/kshook-sv6c/router.ts
- server/src/server/router/api/v1/users/_userID/integrations/router.ts
- server/src/server/router/ir/kshook/sv6c/router.test.ts
- server/src/server/router/ir/kshook/sv6c/router.ts
- server/src/test-utils/mock-db/kshook-sv6c-settings.json
- server/src/test-utils/test-data.ts
> feat: KsHook SV6C Static Importing

- common/src/config/config.ts
- common/src/config/static-config.ts
- common/src/types.ts
- database-seeds/collections/folders.json
- database-seeds/collections/songs-iidx.json
- database-seeds/collections/tables.json
- database-seeds/scripts/rerunners/add-level-version-folders.js
- database-seeds/scripts/rerunners/iidx/iidx-mdb-parse/convert.ts
> feat(seeds): resident support

- common/src/config/config.ts
- server/src/lib/score-import/framework/user-game-stats/builtin-class-handlers.ts
- server/src/lib/score-import/framework/user-game-stats/classes.test.ts
- server/src/lib/score-import/framework/user-game-stats/classes.ts
- server/src/lib/score-import/framework/user-game-stats/update-ugs.ts
- server/src/lib/score-mutation/delete-scores.test.ts
- server/src/lib/score-mutation/delete-scores.ts
- server/src/lib/setup/config.ts
- server/src/test-utils/misc.ts
- server/src/test-utils/test-data.ts
Things like class colours, volforce classes, etc. should
be able to be downgraded if they fall below their requisites.
> feat: allow certain classes to be downgraded

- server/src/lib/score-import/framework/pb/create-pb-doc.test.ts
- server/src/lib/score-import/framework/pb/create-pb-doc.ts
- server/src/lib/score-import/framework/pb/game-specific-merge.ts
Fixes #712
and also patches pms aswell, its neglected cousin
> feat: inherit lamp graphs for bms and bp for bms/pms pbs,

- client/src/app/pages/dashboard/users/NotificationsPage.tsx
- client/src/app/pages/dashboard/users/UserSettingsPage.tsx
- client/src/app/routes/DashboardRoutes.tsx
- client/src/components/layout/header/Topbar.tsx
- client/src/components/layout/header/UserNotificationButton.tsx
- client/src/components/layout/header/UserProfileDropdown.tsx
- client/src/components/notifications/NotificationRow.tsx
- client/src/components/util/Icon.tsx
- common/src/lib/schemas.ts
- common/src/types.ts
- server/src/lib/notifications/notification-wrappers.ts
minimal, but just works (tm)
Fixes #151
> feat: notifications UI

- client/src/app/pages/dashboard/import/SilentHookPage.tsx
instructions for common tools and clarify file placement
> feat: update SilentHookPage instructions

- server/src/lib/jobs/bms-table-sync.ts
Fixes #786.
Local man takes a break from rhythm games to chill out and push out some easier issues.
This isn't really the end of the hiatus, but it's certainly me breaking a couple rules. I think I've had a nice rest and will continue to take a lighter load for the future.
> feat: handle bms table removals

- client/src/app/pages/dashboard/users/games/_game/_playtype/OverviewPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/tools/ToolsPage.tsx
- client/src/app/routes/UserRoutes.tsx
- client/src/components/tools/BMSCustomTablesTool.tsx
- client/src/components/tools/IIDXEamusementExportTool.tsx
- client/src/components/tools/Tools.tsx
- client/src/components/user/UGPTHeader.tsx
- client/src/types/ugpt.ts
- common/src/config/config.ts
- common/src/utils/util.ts
- pnpm-lock.yaml
- server/src/lib/game-specific/custom-bms-tables.ts
- server/src/lib/score-import/import-types/common/eamusement-iidx-csv/parser.ts
- server/src/server/router/api/v1/games/@gameSpecificRoutes/bms/router.ts
- server/src/server/router/api/v1/users/_userID/games/@gameSpecificRoutes/iidx/router.ts
- server/src/server/router/api/v1/users/_userID/games/@gameSpecificRoutes/router.ts
- server/src/server/router/api/v1/users/_userID/games/_game/_playtype/router.ts
bms table selector and iidx eam csv export added as proofs of concept for the functionality.
> feat: ugpt utils

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
- database-seeds/scripts/rerunners/sdvx/add-sdvx-konaste.js
wooooo sorry like a month late it's my birthday today please backport thanks
> add new konaste charts

- common/src/config/config.ts
- common/src/config/versions.ts
- common/src/lib/schemas.ts
- common/src/types.ts
- database-seeds/collections/songs-gitadora.json
- database-seeds/scripts/test/test-utils.ts
- server/src/test-utils/test-data.ts
Add charts for Gitadora konaste 22022101800
> Gitadora konaste charts

- server/example/conf.json5
> Update example conf.json5

- database-seeds/collections/songs-iidx.json
- database-seeds/scripts/rerunners/iidx/add-new-primary-iidx-charts.js
please stop marking my posts as transgender
> updated IIDX DBs for new Infinitas pack

- database-seeds/collections/charts-sdvx.json
just a simple konaste tag addition
> sdvx charts konaste vol19

- server/src/lib/score-import/import-types/ir/barbatos/parser.ts
0 = NOV yet is not parsed causing an "Invalid...Request" error.
> enable barbatos novice imports 

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
Update seeds to include songs from the update pushed on the 27th of April. Also includes some title fixes and additional search terms for songs that did not previously have any.
> update sdvx to 20230425

- .gitignore
> May 2023 Infinitas update

- database-seeds/collections/songs-sdvx.json
Corrected one song title and added alt titles from eamuse csv
> SDVX song title modifications

- .gitignore
- database-seeds/scripts/rerunners/iidx/okapi-inf.js
Holic in Infinitas is proof Konami loves me and wants me to be happy.
ヒマワリ is cool too I guess.
> Added announced June Infinitas unlocks

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
my first time doing this so I hope I didn't break anything lol
> updated seeds for konasute to 2023062100

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
> Konasute db seeds update

- database-seeds/collections/charts-chunithm.json
- database-seeds/collections/songs-chunithm.json
Also adjusts `levelNum` for lower level songs.
> [chunithm] Add seeds for songs that were released at the same time as Japan version

- database-seeds/collections/charts-maimaidx.json
- database-seeds/scripts/rerunners/maimaidx/add-maimaidx-internal-levels.ts
- database-seeds/scripts/rerunners/maimaidx/add-maimaidx-table-and-folders.js
- database-seeds/scripts/rerunners/maimaidx/parse-maimaidx-dataset.js
fill in chart constants for festival plus songs, and update constants for older songs
> [maimaidx] update chart constants

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
wayy too many songs added to write down
> update sdvx to 2023071801

- database-seeds/collections/charts-maimaidx.json
- database-seeds/collections/songs-maimaidx.json
- database-seeds/scripts/rerunners/maimaidx/add-maimaidx-internal-levels.ts
- database-seeds/scripts/rerunners/maimaidx/parse-maimaidx-dataset.js
[said update](https://info-maimai.sega.jp/4155/)
Also filled in chart constants for a few older songs since I was stupid and used the wrong CSV. Sorry!
> [maimaidx] update seeds to 2023-08-04 update

- database-seeds/collections/charts-sdvx.json
Marking existing songs added to konaste on 16/08/23
> New konaste tags

- client/src/app/pages/dashboard/users/games/_game/_playtype/SpecificSessionPage.tsx
- client/src/components/targets/quests/editor/EditableQuest.tsx
- client/src/components/util/EditableText.tsx
A placeholder prop has been added so the component can smoothly handle falsy values
> fix: forgot to update page

- database-seeds/collections/charts-maimaidx.json
- database-seeds/collections/songs-maimaidx.json
4 new songs, 16 new charts. [update information from official website](https://info-maimai.sega.jp/4097/).
> [maimaidx] update seeds to 2023-08-18 update

- database-seeds/collections/charts-maimaidx.json
- database-seeds/collections/songs-maimaidx.json
- database-seeds/scripts/rerunners/maimaidx/add-maimaidx-internal-levels.ts
Should be the final update for FESTiVAL PLUS, I believe.
Update announcement on the official website [here](https://info-maimai.sega.jp/4330/).
New songs:
- 曲：広川恵一 (MONACA)／歌：オンゲキシューターズ - STARRED HEART
- DX Master 12+ (12.5)
- 曲：烏屋茶房／歌：R.B.P. [九條 楓(CV：佳村 はるか)、逢坂 茜(CV：大空 直美)、珠洲島 有栖(CV：長縄 まりあ)] - Y.Y.Y.計画!!!!
- DX Master 13 (13.3)
- USAO - Last Kingdom
- DX Expert 12 (12.5)
- DX Master 13+ (13.8) 
- BlackY - LAMIA
- DX Expert 13 (13.0)
- DX Master 14+ (14.7)
> [maimaidx] update seeds to 2023-09-01

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
new songs :
suspicions - BEMANI Sound Team "Cat Fork Master VS dj TAKA"
THE PEERLESS UNDER HEAVEN - Yuta Imai Vs. BEMANI Sound Team "L.E.D.-G"
stellar rain - BEMANI Sound Team "PHQUASE"
APØCALYPSE RAY - xi
perfect eater - BEMANI Sound Team "PON" feat.Kanatan
power karma - metomate
and many more
(hope i did it right this time)
> sdvx 2023080700

- database-seeds/collections/charts-sdvx.json
script used for https://github.com/TNG-dev/Tachi/pull/935 added a konaste tag where it shouldn't have
> Remove incorrect konaste tag

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
New songs :
KAH feat.こにゃばた - ませまてぃっく♡ま＋ま＝まじっく！　～徹夜の追込みエナジーまっくす！～ 
Alkome - Dawn of Asia(Alkome Remix)
Erica - Demetel (Erixa ”MYTH” Remix) 
かめりあ feat. ななひら - Voice 7 Voice!!!!!!! 
Risk Junk - One More Lovely
C-Show - Please Welcome Mr.c
HHH×MM×ST - Follow Tomorrow
DJ TECHNORCH fw. GUHROOVY  - KAMAITACHI
猫叉Master feat.霜月はるか - Element of SPADA
lapix - Amazing Mirage
後藤 feat. nayuta - リュミレイラ
隣の卓は役満(庭師+Aoi) - 十三不塔
ryhki - SHARK IMPACT
Tatsunoshin - Enter The Rave
polysha - and After the Merry BADEND
RoughSkreamZ - Undead Raving Scare
モリモリあつし - HeaveИ's Rain
BEMANI Sound Team "HuΣeR" - Stylus
BEMANI Sound Team "PHQUASE & ZAQUVA" - QQ
> update sdvx to 2023091200

- client/src/app/pages/dashboard/import/ImportPage.tsx
- client/src/app/pages/dashboard/import/MikadoPage.tsx
- client/src/app/pages/dashboard/import/SaekawaPage.tsx
- client/src/app/routes/ImportRoutes.tsx
- server/src/lib/builtin-clients/builtin-clients.ts
Source code: https://github.com/beerpiss/saekawa
This hook supersedes ChunItachi as an import method.
> Add Saekawa hook as an import method for CHUNITHM

- client/src/app/pages/dashboard/import/AquaArtemisExportPage.tsx
- client/src/app/pages/dashboard/import/ChunithmMYTExportPage.tsx
- client/src/app/pages/dashboard/import/ImportPage.tsx
- client/src/app/routes/ImportRoutes.tsx
a quick PR to add more import methods for chunithm.
- aqua/artemis exporter
- myt web interface scraper/exporter
> feat: more chunithm import methods

- database-seeds/collections/songs-iidx.json
- minor omni fix
- ascii search terms for newer iidx songs
- iidx tierlist data update
I'd like to get some feedback on the tierlist update, and I still need to review it a bit myself.  The tier data is scraped directly from atwiki thanks to some great scripts by @mlaux.  The plan is to eventually fix it up into a rerunner that can be committed.
> IIDX metadata update

- database-seeds/collections/charts-chunithm.json
Marks some songs as available in SUN+ International and SUN Omnimix:
- SEGA Sound Unit[H.] - ジングルベル
- 明坂 芹菜(CV:新田 恵海)＆萩原 七々瀬(CV:東城 日沙子)＆芒崎 奏(CV:立花 理香) - リハーサルタイム
- 山本真央樹 - GEOMETRIC DANCE
> [chunithm] international: update seeds to 2023-12-14

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
this PR includes multiples recents exceed gear updates
2023110700
[ポッピンキャンディ☆フィーバー！](https://remywiki.com/Poppin%27_candy_fever!)
[ポジティブ☆ダンスタイム](https://remywiki.com/Positive_dance_time)
20231205
[=∴NOMADE∵OTION=](https://remywiki.com/ANOMADEVOTION)
[TOKAKU=ALMiRAJ](https://remywiki.com/TOKAKU%3DALMiRAJ)
[随神](https://remywiki.com/Kannagara)
[レインボウ・フレーバー](https://remywiki.com/Rainbow_flavor)
[Burst Λnd reBoost](https://remywiki.com/Burst_And_reBoost)
[OVEЯ+TUЯE](https://remywiki.com/OVER%2BTURE)
[Λkasha](https://remywiki.com/Akasha)
2023121900
[ちくわパフェだよ☆ＣＫＰ (Yvya Remix)](https://remywiki.com/Chikuwa_parfait_da_yo_CKP_(Yvya_Remix))
[めうめうぺったんたん！！ (ZAQUVA Remix)](https://remywiki.com/Meumeupettantan!!_(ZAQUVA_Remix))
> Update SDVX seeds to 2023121900

- database-seeds/collections/charts-maimaidx.json
- database-seeds/collections/songs-maimaidx.json
- collab songs from the new zundamon collab (sega decided to release this collab for both jp and intl on the same date)
- correct more internal levels (apparently my sheet was missing a few things)
- correct isLatest states for charts before buddies
> fix(maimaidx): add collab songs + fixes

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
last two updates for sound voltex
2024011600
[Circuit Surfer](https://remywiki.com/Circuit_Surfer)
[Virtual to LIVE](https://remywiki.com/index.php?title=Virtual_to_LIVE)
[アンチグラビティ・ガール](https://remywiki.com/index.php?title=Antigravity_girl)
[コントレイル](https://remywiki.com/index.php?title=Contrail)
2024013000
https://remywiki.com/AC_SDVX_EG#BEMANI_PRO_LEAGUE_-SEASON_3-!_Original_Song_Contest
[Double or Nothing](https://remywiki.com/index.php?title=Double_or_Nothing)
[We Are All The Dreamer](https://remywiki.com/index.php?title=We_Are_All_The_Dreamer)
> Update sdvx seeds to 2024013000

- server/src/utils/folder.ts
> Folder Raises are off by one

- client/src/components/sessions/SessionRaiseBreakdown.tsx
> raise information shows incorrect "old" middle cells

- client/src/components/layout/header/Header.tsx
> fix: logout button appears when logged out

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
updated konasute seeds to 20240220 thanks to Kanri
> updated konasute seeds to 20240220

- database-seeds/collections/charts-sdvx.json
removed some songs from the exceed gear table according to https://remywiki.com/AC_SDVX_EG#Removed_Songs
> fix : Removed the exceed version from charts removed in exceed gear

- database-seeds/collections/songs-iidx.json
- database-seeds/scripts/rerunners/iidx/mina-inf-legg.js
- database-seeds/scripts/rerunners/iidx/mina-inf.js
Includes the new base exclusives and the CastHour songpack update.
> Infinitas 2024 Update 2: This Time It's Rebased

- package.json
- patches/browserslist@4.21.4.patch
- pnpm-lock.yaml
- server/src/test-utils/hack-setup.js
silence browserslist and mongodb
> fix: remove some extremely annoying deprecation warnings

- client/src/styles/components/navbar.scss
nested templates don't compile, but a mixin does.
> fix: invalid template inside ruleset

- database-seeds/scripts/rerunners/iidx/mina-inf-legg.js
- database-seeds/scripts/rerunners/iidx/mina-inf-new-spl.js
Didn't realize renaming the branch would fuck the PR.
> Added primary charts for new Infinitas exclusive Leggendarias

- database-seeds/scripts/deterministic-collection-sort.js
There might be a cleaner way to do this than just duplicating the first if statement... But it works.
> fix: sink 2dxtra charts to the bottom for real

- common/src/config/game-support/maimai-dx.ts
- database-seeds/collections/charts-maimaidx.json
- database-seeds/collections/songs-maimaidx.json
- database-seeds/scripts/rerunners/maimaidx/merge-options.ts
Changes:
- Add songs from the [final update](https://info-maimai.sega.jp/4882/) of BUDDiES
- Update internal levels, mostly for lower difficulties
> [maimaidx] Update to BUDDiES final

- database-seeds/scripts/rerunners/iidx/mina-inf-new-spl.js
Somehow only Concon stuck the landing the first time???
> [iidx] re-added new Infinitas Leggies

- server/.taprc
- server/src/lib/score-import/import-types/ir/fervidex/converter.ts
- server/src/lib/score-import/import-types/ir/fervidex/types.ts
i don't want to work here anymore
> feat: erosion lamps

- client/src/app/routes/GameRoutes.tsx
- client/src/components/game/charts/ChartInfoFormat.tsx
- common/src/utils/util.ts
> feat: search youtube for stuff

- common/src/config/game-support/chunithm.ts
- database-seeds/collections/charts-chunithm.json
- database-seeds/collections/folders.json
- database-seeds/collections/tables.json
> [chunithm] Add versions NEW and NEW PLUS

- client/src/app/pages/dashboard/import/ImportPage.tsx
- client/src/app/pages/dashboard/import/OngekiArtemisExportPage.tsx
- client/src/app/pages/dashboard/import/OngekiInoharaPage.tsx
- client/src/app/routes/ImportRoutes.tsx
- server/src/lib/builtin-clients/builtin-clients.ts
https://gitea.tendokyu.moe/akanyan/inohara
> feat: add inohara as a default client

- database-seeds/collections/songs-sdvx.json
> fix: incorrect sdvx song title

- bot/src/version.ts
- client/src/app/pages/dashboard/import/ImportPage.tsx
- client/src/app/pages/dashboard/import/USCIRPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/SpecificSessionPage.tsx
- client/src/components/sessions/SessionFolderRaiseBreakdown.tsx
- client/src/components/sessions/SessionOverview.tsx
- client/src/components/tables/components/DropdownRow.tsx
- client/src/components/tables/components/FilterDirectivesIndicator.tsx
- client/src/components/tables/components/TachiTable.tsx
- client/src/components/util/SelectLinkButton.tsx
- client/src/lib/game-implementations.tsx
- client/src/lib/games/arcaea.tsx
- client/src/lib/games/bms-pms.tsx
- client/src/lib/games/gitadora.tsx
- client/src/lib/games/iidx.tsx
- client/src/lib/games/sdvx-usc.tsx
- client/src/lib/types.ts
- docker-compose-dev.yml
- package.json
- server/src/lib/constants/version.ts
just general ui improvements over the course of 2 or 3 hours. that makes an amusing correlation of one-hour-of-work per FAANG rejection i received today.
> feat: things

- database-seeds/collections/charts-chunithm.json
Mark 4 songs as available in LUMINOUS International:
- Stellar Stellar
- アイデン貞貞メルトダウン
- ひめごと*クライシスターズ
- ENERGY SYNERGY MATRIX
[Link to update announcement (Facebook)](https://facebook.com/CHUNITHM.International.ver/posts/976967814435840)
> [chunithm] International June 6th update

- client/src/app/pages/dashboard/import/ImportPage.tsx
the importers work with jp and cn
> Update maimai/chuni import descriptions for official site import to not just intl

- database-seeds/collections/charts-chunithm.json
- database-seeds/collections/songs-chunithm.json
Add updates between 2024/04/25 and 2024/06/06 (final LUMINOUS update).
- https://twitter.com/chunithm/status/1783321682209579420
- https://twitter.com/chunithm/status/1787678932705431994
- https://twitter.com/chunithm/status/1788041235967754325
- https://twitter.com/chunithm/status/1797463270967951822
> [chunithm] Update seeds to 2024/06/06

- common/src/config/game-support/iidx.ts
- database-seeds/scripts/rerunners/iidx/add-2dxtra.js
- database-seeds/scripts/test/id.test.ts
- server/src/lib/score-import/import-types/ir/fervidex/parser.ts
Seeds diff:
https://kamai.tachi.ac/utils/seeds?repo=GitHub%3Azkldi%2FTachi&sha=9f6631d998bb5657522d8a2880c6d3059123ba51&compareRepo=GitHub%3Afluzzarn%2FTachi&compareSHA=d84fa98b648d693bd83d993349b5c85be6375b41
> Add 30-2dxtra version

- database-seeds/collections/charts-chunithm.json
- database-seeds/scripts/rerunners/chunithm/merge-options.ts
Mark songs from the [6/20 international update](https://info-chunithm.sega.com/2750/) as available in LUMINOUS International. Also adds some songs to LUMINOUS Omnimix.
> [chunithm] Update seeds to 2024/06/20

- client/src/components/sessions/SessionOverview.tsx
For games with a single rating algorithm, a session page or the PBs overview page for a given `:game:pt:` would make an identical request, however one would be the data itself, and the other would be the data inside an array. This mismatch causes a crash as the two pages want different data yet are provided with something incorrect when cached from the other page.
We should request an array only if there are more rating algorithms than one, otherwise the identical request is made and cached data is consistent and correctly handled.
The reason I tackled it with this method is because the alternative method of giving the array'd query a unique key will cause unnecessary redundant requests for the same data.
closes #1116
> fix: react-query, same url, different data

- client/src/app/pages/dashboard/games/_game/_playtype/GPTDevInfo.tsx
- client/src/app/pages/dashboard/search/SearchPage.tsx
- client/src/app/pages/dashboard/users/UserGamesPage.tsx
- client/src/app/pages/dashboard/users/UserIntegrationsPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/UGPTSettingsPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/folders/FolderSelectPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/folders/FolderTablePage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/folders/SpecificFolderPage.tsx
- client/src/app/routes/GameRoutes.tsx
- client/src/components/activity/Activity.tsx
- client/src/components/game/folder/FolderInfoHeader.tsx
- client/src/components/game/folder/FolderScoreAverages.tsx
- client/src/components/nav/Navbar.tsx
- client/src/components/sessions/SessionRaiseBreakdown.tsx
- client/src/components/tables/components/FilterDirectivesIndicator.tsx
- client/src/components/tables/components/SelectableCompareType.tsx
- client/src/components/tables/components/TachiTable.tsx
- client/src/components/tables/headers/IndicatorHeader.tsx
Some solutions aren't ideal but any solution is better than no solution to stop the errors.
Especially check typescript usage in `SpecificFolderPage.tsx`. Errors have been cleaned up, just make sure it's what you intended.
> fix: cleanup some react errors

- client/src/components/tables/cells/MaimaiRatingCell.tsx
- client/src/lib/game-implementations.tsx
i deeply apologize for my mistakes
> fix: maimai uses `rate`, actually plug in the wacca cell

- database-seeds/collections/charts-sdvx.json
- database-seeds/collections/songs-sdvx.json
updated sdvx seeds to 2024070900
way too much missing songs since the last tachi update for me to document each one of them sorry
> update sdvx seeds to 2024070900

- database-seeds/collections/charts-sdvx.json
> updated konaste seeds to 17.07.2024

- server/src/scripts/sync-database.ts
Fixes recalculating scores when syncing database seeds.
> fix: correctly derive game name from collection name

- database-seeds/collections/charts-chunithm.json
https://info-chunithm.sega.com/2797/
https://info-chunithm.sega.com/2807/
> [chunithm] update seeds to 2024/08/01

- common/src/config/game-support/gitadora.ts
- seeds/collections/songs-gitadora.json
- seeds/scripts/rerunners/gitadora/parse-mdb.ts
Copied part of the SDVX & DDR Parser to build a parser for Gitadora. 
I've included Fuzz Up seeds in this PR.
> Added Gitadora mdb parser and updated seeds

- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
includes songs from version 2024072300 and 2024080500
> Updated exceed seeds to 2024080500

- seeds/collections/charts-chunithm.json
https://info-chunithm.sega.com/2826/
> [chunithm] Update seeds to 2024-08-23

- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
ac : updated to 20240910
konaste : updated to 20240918 (コナステ版 SOUND VOLTEX BEMANI セレクション 楽曲パック vol.2)
> sdvx seed update (ac and konaste)

- seeds/collections/songs-iidx.json
This adds [Music Pack 25](https://remywiki.com/INFINITAS_music_pack#Music_Pack_vol.25), and the two October monthly songs, Ignis and POWER DREAM, which were announced today.
> feat: update Infinitas through 2024-09

- seeds/collections/charts-chunithm.json
Was busy with things, so this one's pretty late.
https://info-chunithm.sega.com/2876/
> [chunithm] Update seeds to 2024-09-19

- seeds/collections/charts-chunithm.json
https://info-chunithm.sega.com/2903/
> [chunithm] Update seeds to 2024-10-03

- server/src/lib/constants/ea3id.ts
- server/src/lib/score-import/import-types/ir/fervidex/parser.ts
This allows fer imports from IIDX 25, 26, and 26 omnimix.
> feat: enable fer imports for iidx 25, 26, and 26-omni

- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
new songs :
荒谷サトル - Imitated Visions
iru feat. 桃寝ちのい - こどもかくしのアンダーランド
CHUBAY - 憧憬のファンファーレ
隣の庭は青い(庭師+Aoi) - Xinca
打打だいず vs. siromaru - JACK -the KING Ki11ing-
ke-ji - すべてを賭して
technoplanet feat. Tamako Kinoshita - Don't you dare play GOD
> update sdvx seeds to 2024100810

- seeds/collections/charts-chunithm.json
- seeds/collections/charts-maimaidx.json
- seeds/collections/songs-chunithm.json
- seeds/collections/songs-maimaidx.json
This PR adds the qualifier songs for the two game's [official yearly tournament](https://maimai.sega.com/kop6th/maimai_itr_en).
> [maimaidx,chunithm] Update seeds to 2024-10-31

- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
Adds BPL S4 Triple Tribe Phase 1 songs
> updated exceed gear seeds to 20241022

- seeds/collections/charts-popn.json
- seeds/collections/songs-popn.json
Contains all new songs, rerates and removals up until 20240731.
> [popn] Add seeds for pop'n music Unilab up to final version (20240731)

- client/src/lib/games/sdvx-usc.tsx
- common/src/config/game-support/sdvx.ts
- seeds/collections/charts-sdvx.json
- seeds/scripts/rerunners/sdvx/add-sdvx-s-tierlist.ts
This PR adds S grade tierlists from https://sdvx.maya2silence.com/table
https://github.com/user-attachments/assets/de913bc5-82bc-4a04-aebd-456f9638db58
> feat: Add S tierlists for sdvx

- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
also adding S tierlist data since the match failed previously
> fix: sdvx song title

- seeds/collections/songs-maimai.json
- seeds/collections/songs-maimaidx.json
"We are back"
*no results*
"back"
*no results*
???
*checks history*
"we're back!!"
- added some common spelling mistakes & variations (colour/color synergise/synergize)
- added romaji to all songs missing it
- fixed romaji on old songs, tended to have a lot of google translate mistakes
- uncommon characters (eg IAIA★NIGHT) will not return results when searching iaia night, fixed those
> Update maimai search terms

- common/src/config/game-support/iidx.ts
- seeds/collections/folders.json
- seeds/collections/songs-iidx.json
- seeds/collections/tables.json
- seeds/scripts/rerunners/iidx/iidx-mdb-parse/convert.ts
- seeds/scripts/rerunners/iidx/iidx-mdb-parse/merge-mdb.ts
- server/src/lib/score-import/import-types/common/eamusement-iidx-csv/parser.ts
This updates scripts, seeds, and enables eamuse CSV imports for IIDX 32.
> feat: IIDX 32 support

- seeds/collections/charts-sdvx.json
INFINITAS January 2025 Monthly update
- B4U (BEMANI FOR YOU MIX) + LEGG
- Shiva
Also, I got somebody mentioned Houshou Marine for SDVX Konasute. 
I discovered and let me update for you.
> feat. INF JAN 25 update + SDVX Houshou Marine Konasute seed

- seeds/collections/charts-sdvx.json
> feat. SDVX Konaste Song Pack Vol. 24

- seeds/collections/charts-sdvx.json
- seeds/scripts/rerunners/sdvx/add-sdvx-clear-tierlist.js
also updated the script for some more oddities in the spreadsheet files
> update SDVX clear tierlist ratings

- seeds/collections/charts-sdvx.json
these 3 songs were added by https://github.com/zkrising/Tachi/pull/1235 but were also added to konaste
> update sdvx konaste seeds

- seeds/collections/folders.json
The folders should have been copied rather than replaced.
> fix(ongeki): restore previous folders

- seeds/collections/songs-iidx.json
Songs pack will be available on 13 March 2025
But I don't have info about the new exclusive INFINITAS song. but will be updated when it's available.
> [IIDX INF] Song Pack Vol. 26 (RESIDENT)

- client/src/components/game/charts/ChartInfoFormat.tsx
> Fix missing character in でらっくす

- seeds/collections/charts-maimaidx.json
- seeds/collections/songs-maimaidx.json
I missed an option while copy pasting files into the dev container -_-
> [maimai DX] Add missing songs from PRiSM final

- server/src/game-implementations/games/ongeki.test.ts
- server/src/lib/score-import/framework/pb/create-pb-doc.ts
Seems to work on my local instance. Revert the change to `create-pb-doc.ts` and the new test will fail.
> fix: tiebreak ongeki scores based on p-score

- client/src/components/tables/dropdowns/PBDropdown.tsx
- client/src/components/tables/dropdowns/ScoreDropdown.tsx
- client/src/components/tables/dropdowns/components/ChunithmScoreDropdownParts.tsx
- client/src/components/tables/dropdowns/components/DocumentComponent.tsx
- client/src/components/tables/dropdowns/components/OngekiScoreDropdownParts.tsx
The lack of song data goes deeper than I thought. I just sort of gave up and added a query.
Additional slight improvement: the header no longer shows up if no charts are available.
> fix: graph errors

- client/src/app/pages/dashboard/users/games/_game/_playtype/ScoresPage.tsx
- client/src/app/pages/dashboard/users/games/_game/_playtype/UGPTSettingsPage.tsx
Sorry, I thought I had already sent this a while back
> fix: add missing rating name overrides

- seeds/collections/songs-iidx.json
+30 EPOLIS songs from in AC 
+ New 9 INFINITAS Exclusive songs  
+ 1 Revival song. 
Total 40 songs that including in this pack.
> seed: IIDX INFINITAS Song Pack Vol. 27

- .eslintrc
- server/src/lib/score-import/import-types/common/batch-manual/class-handler.ts
- server/src/lib/score-import/import-types/common/batch-manual/parser.test.ts
- server/src/lib/score-import/import-types/common/batch-manual/parser.ts
> fix: broken batch manual classhandler logic

- common/src/config/game-support/maimai-dx.ts
- server/src/game-implementations/games/_common.ts
- server/src/game-implementations/games/maimaidx.test.ts
- server/src/game-implementations/games/maimaidx.ts
This should fix stuff that uses the formatter i.e. stat showcase.
> [maimaidx] use 4dp for percent formatter

- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
- seeds/scripts/rerunners/sdvx/merge-mdb.ts
> feat: merge sdvx2 and sdvx3 mdb

- docs/docs/wiki/games.md
- docs/docs/wiki/rules.md
Added missing data, fixed strange casing, rearranged the games to fit the site order
> docs: update game list and controller rules

- client/src/lib/games/sdvx-usc.tsx
- common/src/config/game-support/sdvx.ts
- seeds/collections/charts-sdvx.json
- seeds/collections/songs-sdvx.json
- seeds/scripts/rerunners/sdvx/merge-mdb.ts
0271_vallis_djyoshitaka
0272_im_so_happy_ryu
0315_koihadou_avenue
0636_everlasting_penoreri
0699_elpis_djtaka
2240_explore_haruichiban
2241_aobanoashioto_dagashiogata
2242_hihouwaineat_shu
2243_gyagyagya_tsukimiguu
2244_kakugoseyo_makishiukyou
2245_icecreammagic_yukinoito
2251_wakuseiloop_kagasumire
This update also introduces ult (ultimate) difficulty and I tried to implement.
> seeds: update sdvx to 20250624 + add ult difficulty
